# Copyright 2026 Muhammad Ureed Hussain
# SPDX-License-Identifier: Apache-2.0

"""Launch only reviewed ROS package examples with literal argument vectors."""

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import shutil
import signal
import subprocess
import sys
import termios
from typing import Optional, Tuple

from .named_tasks import _unique_object


class ExampleError(ValueError):
    """Reject an invalid registry, ambiguous request or launch prerequisite."""


@dataclass(frozen=True)
class ExampleProgram:
    """One reviewed executable or launch file, never text generated by a model."""

    name: str
    aliases: Tuple[str, ...]
    description: str
    kind: str
    package: str
    target: str
    arguments: Tuple[str, ...]
    requires_driver: bool
    requires_joint_states: bool
    conflict_nodes: Tuple[str, ...]

    @property
    def argv(self) -> Tuple[str, ...]:
        """Return the fixed ROS command, without a shell or prompt additions."""
        return ("ros2", self.kind, self.package, self.target, *self.arguments)


@dataclass(frozen=True)
class ExampleRequest:
    """Request a list, a preview or a specific program."""

    operation: str
    name: str = ""


def _text(value, limit=500):
    if (
        not isinstance(value, str) or not value.strip() or len(value) > limit
        or any(ord(char) < 32 or ord(char) == 127 for char in value)
    ):
        raise ExampleError("Registry strings must be bounded printable text")
    return value


def _identifier(value):
    if not re.fullmatch(r"[a-z][a-z0-9_]{0,63}", _text(value, 64)):
        raise ExampleError("Example/package name must be a lowercase identifier")
    return value


def _words(value):
    return " ".join(value.lower().replace("_", " ").split())


class ExampleCatalog:
    """Load one bounded registry once; changing it requires a restart."""

    def __init__(self, path: str):
        source = Path(path).expanduser().resolve(strict=True)
        if not source.is_file():
            raise ExampleError("example_registry_file must be a file")
        with source.open("rb") as stream:
            raw = stream.read(65537)
        if len(raw) > 65536:
            raise ExampleError("Example registry exceeds 64 KiB")
        try:
            data = json.loads(raw.decode("utf-8"), object_pairs_hook=_unique_object)
        except (ValueError, UnicodeError, RecursionError) as exc:
            raise ExampleError(f"Invalid example JSON: {exc}") from exc
        if not isinstance(data, dict) or set(data) != {
            "schema_version", "examples"
        }:
            raise ExampleError("Registry needs only schema_version and examples")
        if type(data["schema_version"]) is not int or data["schema_version"] != 1:
            raise ExampleError("Example schema_version must be integer 1")
        entries = data["examples"]
        if not isinstance(entries, list) or len(entries) > 64:
            raise ExampleError("examples must be a list of at most 64 entries")
        self._programs = {}
        self._aliases = {}
        for entry in entries:
            program = self._decode(entry)
            if program.name in self._programs:
                raise ExampleError(f"Duplicate example: {program.name}")
            for alias in (program.name, *program.aliases):
                key = _words(alias)
                if key in self._aliases:
                    raise ExampleError(f"Duplicate/ambiguous example alias: {alias}")
                self._aliases[key] = program.name
            self._programs[program.name] = program
        self.source = str(source)
        self.sha256 = hashlib.sha256(raw).hexdigest()

    @staticmethod
    def _decode(entry):
        required = {
            "name", "aliases", "description", "kind", "package", "target",
            "arguments", "requires_driver", "requires_joint_states",
            "conflict_nodes",
        }
        if not isinstance(entry, dict) or set(entry) != required:
            raise ExampleError("Example entry has missing or unexpected fields")
        name = _identifier(entry["name"])
        package = _identifier(entry["package"])
        description = _text(entry["description"])
        kind = entry["kind"]
        if kind not in ("run", "launch"):
            raise ExampleError("Example kind must be run or launch")
        target = _text(entry["target"], 128)
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_.-]*", target) or ".." in target:
            raise ExampleError("target must be a package filename, not a path")
        if kind == "launch" and not target.endswith((".py", ".xml", ".yaml")):
            raise ExampleError("Launch target must be a Python/XML/YAML file")
        for key in ("requires_driver", "requires_joint_states"):
            if type(entry[key]) is not bool:
                raise ExampleError(f"{key} must be a boolean")
        if entry["requires_joint_states"] and not entry["requires_driver"]:
            raise ExampleError("Joint state checking requires the existing driver")
        for key in ("aliases", "arguments", "conflict_nodes"):
            if not isinstance(entry[key], list) or len(entry[key]) > 64:
                raise ExampleError(f"{key} must be a bounded list")
        aliases = tuple(_text(item, 80) for item in entry["aliases"])
        if any(not re.fullmatch(r"[a-z][a-z0-9_ ]*", a) for a in aliases):
            raise ExampleError("Aliases may contain lowercase words/numbers only")
        arguments = tuple(_text(item) for item in entry["arguments"])
        conflicts = tuple(_text(item, 128) for item in entry["conflict_nodes"])
        if any(not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", n) for n in conflicts):
            raise ExampleError("conflict_nodes must contain ROS node basenames")
        return ExampleProgram(
            name, aliases, description, kind, package, target, arguments,
            entry["requires_driver"], entry["requires_joint_states"], conflicts,
        )

    @property
    def names(self):
        """Return available canonical names."""
        return tuple(self._programs)

    def resolve(self, text: str) -> Optional[str]:
        """Resolve only explicitly listed aliases, without fuzzy inference."""
        return self._aliases.get(_words(text))

    def get(self, name: str) -> ExampleProgram:
        """Look up a canonical name without opening a prompt-supplied path."""
        if name not in self._programs:
            raise ExampleError(f"Unknown example {name!r}; use /examples")
        return self._programs[name]

    def mentions(self, text: str) -> bool:
        """Detect a known program in an otherwise invalid/negated request."""
        normalized = _words(text)
        return any(re.search(r"\b" + re.escape(alias) + r"\b", normalized)
                   for alias in self._aliases)


def parse_example_request(prompt: str, catalog: ExampleCatalog):
    """Accept friendly exact example requests; never alter their arguments."""
    text = " ".join(prompt.lower().split()).rstrip(".!?")
    if text in {
        "/examples", "examples", "list examples", "show examples",
        "show me the examples", "what examples can i run",
        "which examples can i run",
    }:
        return ExampleRequest("list")
    match = re.fullmatch(
        r"(?:(?:please|can you|could you|would you|can u|could u)\s+)*"
        r"(?P<verb>run|start|launch|open|execute|preview|/example|/preview)\s+"
        r"(?:the\s+)?(?P<name>.+?)(?:\s+for me)?(?:\s+please)?", text
    )
    if not match:
        if catalog.mentions(text):
            raise ExampleError(
                "No example was started. Use 'run NAME example', "
                "'preview NAME example', or /ask for advice."
            )
        return None
    name = re.sub(r"^(?:example|program)\s+", "", match["name"])
    name = re.sub(r"\s+(?:example|program|demo)$", "", name)
    canonical = catalog.resolve(name)
    if canonical:
        return ExampleRequest(
            "preview" if "preview" in match["verb"] else "run", canonical
        )
    if match["verb"] == "/example":
        raise ExampleError("Unknown example; use /examples for exact names")
    if catalog.mentions(text):
        raise ExampleError(
            "Choose one exact example without extra arguments, targets, "
            "speed changes or chained commands. Use /examples for the list."
        )
    return None


def check_conflicts(program: ExampleProgram, node_names) -> None:
    """Reject known duplicates/conflicts without stopping other processes."""
    conflicts = set(program.conflict_nodes).intersection(node_names)
    if conflicts:
        raise ExampleError(
            "Already running/conflicting ROS nodes: "
            + ", ".join(sorted(conflicts))
            + ". Close the other example only after motion is finished. "
            "I will not kill another process."
        )


def run_foreground(program: ExampleProgram, popen=None) -> int:
    """Give the child the terminal until exit, retaining assistant SIGINT state."""
    if not sys.stdin.isatty():
        raise ExampleError("Opening an example requires an interactive terminal")
    ros2 = shutil.which("ros2")
    if ros2 is None:
        raise ExampleError("ros2 is unavailable; source ROS and this workspace")
    argv = (ros2, *program.argv[1:])
    fd = sys.stdin.fileno()
    original_terminal = termios.tcgetattr(fd)
    original_sigint = signal.getsignal(signal.SIGINT)
    child = None
    try:
        termios.tcflush(fd, termios.TCIFLUSH)
        # Spawn before ignoring SIGINT: the child must not inherit SIG_IGN.
        child = (popen or subprocess.Popen)(argv, shell=False)
        signal.signal(signal.SIGINT, signal.SIG_IGN)
        return child.wait()
    except KeyboardInterrupt:
        # A launch-window interrupt is not an emergency stop or a retry.
        if child is not None:
            signal.signal(signal.SIGINT, signal.SIG_IGN)
            return child.wait()
        raise
    except OSError as exc:
        raise ExampleError(
            f"Could not start/wait for the example: {exc}. Check for a "
            "remaining child process and controller motion before retrying."
        ) from exc
    finally:
        try:
            termios.tcsetattr(fd, termios.TCSADRAIN, original_terminal)
            termios.tcflush(fd, termios.TCIFLUSH)
        finally:
            signal.signal(signal.SIGINT, original_sigint)
