# Copyright 2026 Muhammad Ureed Hussain
# SPDX-License-Identifier: Apache-2.0

"""Small package-specific conversation guide with no tools or model calls."""

from dataclasses import dataclass
import re
from typing import Optional


@dataclass(frozen=True)
class HelpTopic:
    """Reviewed explanation and read-only checks, not runtime observations."""

    summary: str
    checks: str
    source: str


TOPICS = {
    "examples": HelpTopic(
        "Use /examples to list actual ROS programs, then 'run teleop "
        "example' or 'run moveit2 example'. The selected program takes "
        "over this terminal until it exits. This is separate from the "
        "single-step JSON motion tasks listed by /tasks.",
        "Opening a program needs --execute, its exact name in "
        "allowed_examples and typed LAUNCH confirmation. Teleop starts "
        "disarmed; SPACE arms it and Q exits after the current jog. "
        "MoveIt opens the M-10iA GUI using the existing driver, not another "
        "driver or mock joint publisher. Close conflicting example nodes "
        "first. Ctrl+C/process exit is not a robot stop. Other reviewed "
        "ROS programs can be registered in example_registry_file; no "
        "command or launch argument is generated by the language model.",
        "fanucpy_ros2_assistant/README.md#ros-example-programs",
    ),
    "tasks": HelpTopic(
        "You can run a reviewed JSON task by name. Try /tasks, then "
        "'preview move_left_demo' or 'please run the move left example'. "
        "A task is one status query, relative jog, absolute Cartesian target, "
        "or TP call. It is not a Python script or shell command.",
        "Task files are loaded once at startup from task_directory. "
        "Motion additionally needs allowed_tasks, --execute, the applicable "
        "driver gates, fresh feedback and typed confirmation. Preview first. "
        "Task values cannot be overridden conversationally. Review/edit "
        "the file yourself and restart to load changes; no automatic retry.",
        "fanucpy_ros2_assistant/README.md#named-task-files",
    ),
    "vision": HelpTopic(
        "Unavailable vision does not mean an empty scene. This assistant "
        "needs fresh /fanuc/vision/detections from the vision bridge, which "
        "in turn needs the external detector's observations. I have not "
        "checked your live publishers from this help question.",
        "Read-only checks:\n"
        "  ros2 topic info /fanuc/vision/detections -v\n"
        "  ros2 topic info /danger/model/observations -v\n"
        "  ros2 topic echo /fanuc/vision/status --once\n"
        "With no publisher, check that the corresponding node is running "
        "in the same ROS environment/domain. With publishers present, check "
        "message timestamps, bridge diagnostics and freshness. Do not "
        "disable freshness checks to make object motion work.",
        "docs/interfaces.md#published-topics; "
        "fanucpy_ros2_vision_bridge/README.md",
    ),
    "connection": HelpTopic(
        "A connection error needs the exact driver log to diagnose. "
        "A refused connection can indicate that the configured endpoint "
        "is not accepting connections; a timeout alone does not establish "
        "whether a robot movement finished. Never automatically repeat it.",
        "Read-only checks:\n"
        "  ros2 topic echo /fanuc/driver_status --once\n"
        "  ros2 node list\n"
        "Check the configured robot address/port and whether the required "
        "MAPPDK server is available. Share the exact error and whether it "
        "happened during connection, state reading, movement or a TP call. "
        "Redact private network details before sharing logs publicly.",
        "docs/controller_setup.md; docs/interfaces.md#parameters",
    ),
    "gates": HelpTopic(
        "A disabled execution gate is an intentional permission check, "
        "not necessarily a fault. The assistant starts in dry-run mode. "
        "--execute does not override driver gates, workflow gates, "
        "allowlists or the confirmation step. I will not enable them for you.",
        "Use /status for current feedback, and copy the exact blocked "
        "parameter from the message. Read config/assistant.yaml and the "
        "supervised-execution section of this package's README. A named "
        "task also needs its exact identifier in allowed_tasks. Only change "
        "permissions after reviewing the task and workcell; changing "
        "configuration requires the relevant node to be restarted.",
        "fanucpy_ros2_assistant/README.md#supervised-physical-execution; "
        "docs/interfaces.md",
    ),
    "units": HelpTopic(
        "Native Cartesian commands use X/Y/Z in millimetres and W/P/R "
        "in degrees. /joint_states uses radians; the conversational "
        "six-joint target uses degrees. 'move X 300' is absolute; "
        "'move X by 10 mm' is relative. Missing absolute axes preserve "
        "fresh feedback. The frame label does not perform a TF transform.",
        "Read-only checks:\n"
        "  ros2 interface show fanucpy_ros2_interfaces/action/MoveCartesian\n"
        "  ros2 interface show fanucpy_ros2_interfaces/action/JogCartesian\n"
        "Confirm active controller frame/tool and calibration before "
        "motion. Vision's affine mapping provides X/Y only, not depth or Z.",
        "docs/interfaces.md; fanucpy_ros2_task_planner/README.md",
    ),
    "pick": HelpTopic(
        "In this package, 'pick' is a motion-only approach, vertical "
        "descent and retraction. 'Drop' moves to the configured pose. "
        "Neither operates a gripper or verifies an object was grasped. "
        "Vision workflows require a stationary object/conveyor.",
        "Review pick_approach_z_mm, pick_descend_z_mm, pick_retract_z_mm "
        "and drop_target_mm_deg in your assistant parameters. These are "
        "workcell-specific values, not safe defaults for other robots. "
        "The workflow does not calculate collisions, object height or "
        "tool clearance. Use a dry-run preview before considering motion.",
        "fanucpy_ros2_assistant/README.md",
    ),
    "tp": HelpTopic(
        "'Go home' requests the configured home_program_name; an explicit "
        "TP call uses /fanuc/run_program. The program must already exist "
        "on the controller and be in the driver's allowed_tp_programs. "
        "Its movements and speed come from that controller program.",
        "Read-only checks:\n"
        "  ros2 action info /fanuc/run_program\n"
        "  ros2 topic echo /fanuc/driver_status --once\n"
        "Home also needs enable_home_program_call. Program success followed "
        "by connection recovery failure must not trigger an automatic "
        "repeat. This assistant cannot inspect the controller's TP source "
        "or determine an alarm's meaning without matching documentation.",
        "docs/interfaces.md#tp-programs; fanucpy_ros2_assistant/README.md",
    ),
    "ollama": HelpTopic(
        "Ollama interprets conversational commands; the host validates "
        "them. Package help and JSON tasks do not need a model response. "
        "A model/JSON error is not evidence that a robot action was sent.",
        "Check that your selected model is installed with 'ollama list' "
        "and that ollama_url/ollama_model match your local setup. Share "
        "the exact prompt and error for invalid model output. Do not "
        "remove command validation to accept a malformed response. A "
        "second 'ollama serve' may report an occupied port when the "
        "installed Ollama service is already running.",
        "fanucpy_ros2_task_planner/OLLAMA.md; "
        "fanucpy_ros2_task_planner/ollama_client.py",
    ),
    "build": HelpTopic(
        "Use the ROS 2 Humble environment and this workspace's overlay "
        "in each terminal. A missing package/executable can mean that "
        "the package was not built or the intended overlay was not sourced; "
        "the exact terminal error is needed to distinguish those cases.",
        "Read-only checks:\n"
        "  ros2 pkg prefix fanucpy_ros2_assistant\n"
        "  ros2 pkg executables fanucpy_ros2_assistant\n"
        "See this package's README for build/source commands. For a code "
        "issue, paste the traceback, relative filename and relevant code "
        "excerpt with secrets removed. I do not automatically open, edit "
        "or execute local files.",
        "fanucpy_ros2_assistant/README.md#build",
    ),
    "scope": HelpTopic(
        "I can help with this fanucpy_ros2 package: setup, interfaces, "
        "units, vision availability, execution gates, TP calls and named "
        "tasks. I can also preview supported robot requests. I am not an "
        "official FANUC support service or a general controller-manual bot.",
        "Try 'why is vision unavailable?', 'explain the coordinate units', "
        "'how do I run an example?' or '/tasks'. For a problem, give the "
        "exact command, error and package/file involved. This first help "
        "version is a reviewed package guide, not an arbitrary-code debugger. "
        "Use /status for actual feedback. Help replies never send commands, "
        "change parameters, run terminal checks or modify files.",
        "fanucpy_ros2_assistant/README.md#package-help",
    ),
}


class PackageConversation:
    """Remember only a help topic; never carry pending motion permission."""

    def __init__(self):
        self._topic = None

    def clear(self):
        """Forget the help context without modifying robot state."""
        self._topic = None

    def reply(self, prompt: str) -> Optional[str]:
        """Answer local help/small-talk, or leave robot/vision intent alone."""
        text = " ".join(prompt.lower().split()).rstrip(".!?")
        if text in {"hi", "hello", "hey", "hello assistant", "good morning"}:
            return (
                "Hello! I can help with this package, show robot/vision "
                "information, or preview a task. What would you like to do? "
                "Try /tasks, /examples or ask a package question."
            )
        if text in {"thanks", "thank you", "thankyou", "great", "okay", "ok"}:
            return "You're welcome. No robot command was sent."
        if text in {"yes", "do it", "again", "repeat", "run it"}:
            return (
                "Please name the task or give the movement again. I won't "
                "use a short acknowledgement to repeat a robot command. "
                "Use /tasks to see the available tasks."
            )
        if text in {"stop", "stop now", "cancel", "emergency stop"}:
            return (
                "This chat cannot reliably stop physical motion. Use "
                "pendant HOLD or emergency stop. No stop command was sent."
            )
        followup = text in {
            "/more", "more", "tell me more", "explain more",
            "how do i check that", "what should i check", "what next",
            "how do i fix it", "how to fix it", "how can i fix it",
        }
        if followup and self._topic:
            topic = TOPICS[self._topic]
            return f"{topic.checks}\nPackage reference: {topic.source}"
        explicit = text.startswith("/ask")
        question = bool(re.match(
            r"(?:why\b|how (?!many\b)|explain\b|help\b|help me\b|"
            r"(?:can|could|would) (?:you|u) (?:please )?(?:explain|help|"
            r"tell me (?:how|why|about))\b|"
            r"what (?:can you do|does .* mean)|i (?:am|'m) stuck)", text
        ))
        technical = bool(re.search(
            r"\b(error|traceback|exception|failed|unavailable|disabled|"
            r"troubleshoot|troubleshooting|not working|help|issue)\b", text
        ))
        if not (explicit or question or technical or followup):
            return None
        if explicit:
            text = text[4:].strip()
        key = "scope"
        for candidate, pattern in (
            ("examples", r"teleop|moveit|movite|launch.*example|ros.*program"),
            ("vision", r"vision|detect|camera|publisher|empty scene"),
            ("gates", r"gate|disabled|enable_|blocked|permission|dry.run"),
            ("connection", r"connect|timeout|timed out|refused|socket"),
            ("units", r"units?|frame|coordinate|radian|degree|absolute|relative"),
            ("tp", r"\btp\b|home|run_program|program"),
            ("pick", r"pick|drop|gripper|grasp"),
            ("ollama", r"ollama|qwen|model|json|llm"),
            ("tasks", r"task|example|run.*file"),
            ("build", r"build|colcon|source|launch|code|file|\.py|install"),
        ):
            if re.search(pattern, text):
                key = candidate
                break
        self._topic = key
        topic = TOPICS[key]
        return (
            f"{topic.summary}\nAsk 'tell me more' for checks and details.\n"
            f"Package reference: {topic.source}"
        )
